### ISSUE TITLE
Microsoft.Azure.Management.Consumption.Models.ErrorResponseException

### ISSUE THREAD

**Issue by Chrisgin10** [Azure-Samples/Cost-Management-Samples#2]
### This issue is for a: (mark with an `x`)

- [ ] bug report .

### Minimal steps to reproduce
I input my Free-trail Azure subscription Id to test the app, but it still throws the exception. Is this because of lacking permission? But I don't find any entrance to permit.
By the way, my main propose is to get the price sheet of an internal subscription. However, I got status code "422 Unprocessable Entity".

### Any log messages given by the failure
Microsoft.Azure.Management.Consumption.Models.ErrorResponseException
  HResult=0x80131500
  Message=Operation returned an invalid status code 'NotFound'
  Source=Microsoft.Azure.Management.Consumption
  StackTrace:
   at Microsoft.Azure.Management.Consumption.PriceSheetOperations.<GetWithHttpMessagesAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Consumption.PriceSheetOperationsExtensions.<GetAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Consumption.PriceSheetOperationsExtensions.Get(IPriceSheetOperations operations, String expand, String skiptoken, Nullable`1 top)
   at CostManagementHelloWorld.Program.GetFullPriceSheet(ConsumptionManagementClient consumptionClient) in C:\Users\t-wal\Documents\Azure\Cost-Management-Samples\helloworld-dotnet\CostManagementHelloWorld\Program.cs:line 218
   at CostManagementHelloWorld.Program.Main(String[] args) in C:\Users\t-wal\Documents\Azure\Cost-Management-Samples\helloworld-dotnet\CostManagementHelloWorld\Program.cs:line 45

### Expected/desired behavior
I have used the Free-Trail SubscriptionId. So the price sheet should be shown.

### OS and Version?
> Windows 10

### Mention any other details that might be useful
I'll be appreciated if you could any information about how to get daily cost report of an internal subscription!

**Comment by sabuncu** [comment]
This issue is still open since Feb 19.  Does this mean this repo is unattended? Thanks.
